### ISSUE TITLE
AttributeError: '_idat' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by yanarizzieri** [gchchung/TeloSearchLR#1]
Hey George,

I'm pretty excited with TeloSearchLR!!!!! 

I was trying to run the test dataset earlier today and got stuck on an error. It seems like it's a python error, as I found something simillar on this [discussion](https://github.com/python-pillow/Pillow/issues/3208), but I couldn't solve it. I tried downgrading the laxml version from 5.3.0 to 5.1.0, but that did not change anything. Any suggestions? 

Code I'm running: `TeloSearchLR.py -f SRR7594465.fasta -k 4 -K 20 -m 1 -M 100 -n 6000`

Log screenshot:
<img width="952" alt="Screenshot 2024-11-04 at 1 48 12 PM" src="https://github.com/user-attachments/assets/902f65db-842d-4ed1-960f-6137d6645891">

Log file:
[telomere.log](https://github.com/user-attachments/files/17622591/telomere.log)

The output files have the heathers, but otherwise are empty:
<img width="1019" alt="Screenshot 2024-11-04 at 2 05 57 PM" src="https://github.com/user-attachments/assets/b49c66fc-798e-42be-9bf3-9644b52a10fd">

Thank you,

Y

**Comment by gchchung** [comment]
It looks like Pillow (for making PNG output) is throwing the exception. May need to downgrade Pillow in the environment, or update my code to use Pillow v11.0.0. But strange that some of the *.txt are empty files. I am attempting to replicate the problem. Could you show me

1. Your install commands
2. Screencap of the *.results folder (it likely will have some .txt files)
3. Screencap the first few lines of TeloSearchLR.k4.K20.t1000.SRR7594465.rankedRepeatsTable.txt (eg. use `head -50 TeloSearchLR.k4.K20.t1000.SRR7594465.rankedRepeatsTable.txt`)

**Comment by gchchung** [comment]
Hi @yanarizzieri , I have not been able to replicate your Pillow exception, as the newer Pillow (v11.0.0) appears to work as well. However, I did notice that the `meta.yaml` in my bioconda recipe did not include `python-kaleido` and may have given an error. While I try to replicate this error, may I suggest trying following fresh install.

1. Deactivate the `telosearchlr-env` if it's still running.
`conda deactivate`
2. Remove the environment on your disk. Press 'y' when prompted to delete everything.
`conda remove --name telosearchlr-env --all`
3. Re-create the environment
`conda create -n telosearchlr-env -y -c bioconda telosearchlr`
4. Activate the environment
`conda activate telosearchlr-env`
**5. Additionally, install `python-kaleido` using conda while in the `telosearchlr-env`**
`conda install -c conda-forge -y python-kaleido`
6. Now try to run the script
`TeloSearchLR.py -f SRR7594465.fasta -t 1000 -k 4 -K 20 -m 1 -M 100 -n 6000`

**Comment by yanarizzieri** [comment]
George,

I'm still getting the same error (attached in the end) after re-creating the conda env and re-installing telosearchlr. 

To follow with your questions I have attached a screen short of the empty (I know) .results directory:
.results Directory:
<img width="770" alt="Screenshot 2024-11-04 at 6 14 46 PM" src="https://github.com/user-attachments/assets/8924787b-3d65-466a-8150-433bf64ea88e">

And I have attached the file: `TeloSearchLR.k4.K20.t1000.SRR7594465.rankedRepeatsTable.txt` that only contains the header
[TeloSearchLR.k4.K20.t1000.SRR7594465.rankedRepeatsTable.txt](https://github.com/user-attachments/files/17624876/TeloSearchLR.k4.K20.t1000.SRR7594465.rankedRepeatsTable.txt)

I also tried running Pillow on v.10.4.0, but got the same error.

Finally, I added a list with all programs (`conda list`) to look for things that can be wrong (if you send yours I do not mind looking for differences). 

# Name | Version
_libgcc_mutex | 0.1
_openmp_mutex | 4.5
bio | 1.7.1
biopython | 1.84
biothings_client | 0.2.6
brotli-python | 1.1.0
bzip2 | 1.0.8
ca-certificates | 2024.8.30
certifi | 2024.8.30
cffi | 1.17.1
charset-normalizer | 3.4.0
colorama | 0.4.6
expat | 2.6.3
font-ttf-dejavu-sans-mono | 2.37
font-ttf-inconsolata | 3
font-ttf-source-code-pro | 2.038
font-ttf-ubuntu | 0.83
fontconfig | 2.15.0
fonts-conda-forge | 1
freetype | 2.12.1
gprofiler-official | 1.0.0
h2 | 4.1.0
hpack | 4.0.0
hyperframe | 6.0.1
idna | 3.1
kaleido-core | 0.2.1
lcms2 | 2.16
ld_impl_linux-64 | 2.43
lerc | 4.0.0
libblas | 3.9.0
libcblas | 3.9.0
libdeflate | 1.22
libexpat | 2.6.3
libffi | 3.4.2
libgcc | 14.2.0
libgcc-ng | 14.2.0
libgfortran | 14.2.0
libgfortran-ng | 14.2.0
libgfortran5 | 14.2.0
libgomp | 14.2.0
libiconv | 1.17
libjpeg-turbo | 3.0.0
liblapack | 3.9.0
libnsl | 2.0.1
libopenblas | 0.3.28
libpng | 1.6.44
libsqlite | 3.47.0
libstdcxx | 14.2.0
libstdcxx-ng | 14.2.0
libtiff | 4.7.0
libuuid | 2.38.1
libwebp-base | 1.4.0
libxcb | 1.17.0
libxcrypt | 4.4.36
libxml2 | 2.13.4
libxslt | 1.1.39
libzlib | 1.3.1
lxml | 5.3.0
mathjax | 2.7.7
mygene | 3.2.2
ncurses | 6.5
nspr | 4.36
nss | 3.106
numpy | 2.1.3
openjpeg | 2.5.2
openssl | 3.3.2
packaging | 24.1
pandas | 2.2.3
pillow | 11.0.0
pip | 24.3.1
platformdirs | 4.3.6
plotly | 5.24.1
pooch | 1.8.2
pthread-stubs | 0.4
pycparser | 2.22
pysocks | 1.7.1
python | 3.12.7
python-dateutil | 2.9.0
python-kaleido | 0.2.1
python-tzdata | 2024.2
python_abi | 3.12
pytz | 2024.1
readline | 8.2
requests | 2.32.3
setuptools | 75.3.0
six | 1.16.0
sqlite | 3.47.0
svgutils | 0.3.4
telosearchlr | 1.0.1
tenacity | 9.0.0
tidehunter | 1.5.5
tk | 8.6.13
tqdm | 4.66.6
tzdata | 2024b
urllib3 | 2.2.3
wheel | 0.44.0
xorg-libxau | 1.0.11
xorg-libxdmcp | 1.1.5
xz | 5.2.6
zstandard | 0.23.0
zstd | 1.5.6

Error message after new installation and new conda env:
<img width="1080" alt="Screenshot 2024-11-04 at 6 11 17 PM" src="https://github.com/user-attachments/assets/a33a74de-c0d0-499b-a785-688cfb4abe9a">

Y

**Comment by gchchung** [comment]
Thanks. The "tile cannot extend outside image" error happens when the image dimensions are wrong. This could be because there's no TideHunter search result file to construct any plots. In your previous run, it looked like the `*.TideHunterTable.txt` files were empty, so this could explain the tiling error. I also noticed that this run has "Illegal instruction" at every TideHunter call (Steps 2 and 3). Finally, I am not sure what might be causing the `fp.fileno()` error.

Without doing another run, could I get you to try a few things?

1. In the directory of the reads (ie. where SRR7594465.fasta is), could you show me the output of `ls -ahl`. I would like to see which files are missing/empty this time.
2. In your telosearchlr environment, could you show me the output of either `type TideHunter` or `which TideHunter`? If installed through conda, it should read something like `/home/PATH_TO_ENVIRONMENT/telosearchlr-env/bin/TideHunter`.

Let me know :) Thanks for your patience.

**Comment by yanarizzieri** [comment]
1.  this is the output of `ls -ahl` 
<img width="748" alt="Screenshot 2024-11-04 at 7 15 02 PM" src="https://github.com/user-attachments/assets/baecd07b-9874-4188-b8a8-9238092c4095">

2. output for `type TideHunter`
TideHunter is /home/yana/miniforge3/envs/telosearchlr-env/bin/TideHunter

3. output for `TideHunter -p 4 -P 20 -f 2 -m 4 SRR7594465.fasta > TideHunter_test.txt`
<img width="612" alt="image" src="https://github.com/user-attachments/assets/8313c533-4315-411f-b25d-c2794caacba4">

4. TideHunter_test.txt is empty!
<img width="741" alt="Screenshot 2024-11-04 at 7 22 10 PM" src="https://github.com/user-attachments/assets/e92ba645-c823-4521-abd6-e54f821de95d">

5. On the TideHunter forum [https://github.com/Xinglab/TideHunter/issues/19](url) they are calling my server old LOL. I have access to a new work station, I'll try in the morning, but it looks like it's between my server and TideHunter!

Thank you so much George!

**Comment by gchchung** [comment]
This would be it! Illegal instruction comes from a bad compilation of TideHunter. Old CPU could be the culprit. I will add a blurb about this in the README if you are able to provide more details on this CPU.

This would be why there were no TideHunter search results both times (TideHunter_test.txt and the *.TideHunterTable.txt). Without the search results, TeloSearchLR could not generate a list of the most frequent repeat patterns at the sequencing read ends. And without this list, the filehandles for Pillow gave the errors you saw.

I think TideHunter is pretty lean and a workstation should be able to run it!

**Comment by gchchung** [comment]
@yanarizzieri you should also be able to get around the old CPU by using the containerized copy of the code (Docker), if your server has more compute power/storage than your workstation. If there are other issues unrelated to this, please feel free to raise them!

**Comment by yanarizzieri** [comment]
Just as an add up in case somebody else encounters the same problem, I did install it on the new workstation, but using the manual `conda install` code was giving me an error because of some package versions. After creating the environment, I had to `conda install` biopython, tqdm, urllib3, pillow and svgutils individually. Also, had to `pip install -U kaleido`, and now everything is running fine!!!!
